begin;
select set_config('request.jwt.claims','{"role":"service_role","sub":"10000000-0000-4000-8000-000000000001"}',true);
do $$declare a uuid:='10000000-0000-4000-8000-000000000001'; b uuid:='10000000-0000-4000-8000-000000000002';
 c uuid:='10000000-0000-4000-8000-000000000003'; result jsonb; stamp text;
begin
 result:=public.manage_portal_accounts(a,'list');
 assert (result->>'total')::integer=3,'Directory count';
 assert not (result->'users'->0 ? 'raw_app_meta_data'),'No metadata disclosure';
 begin perform public.manage_portal_accounts(c,'list'); raise exception 'Company directory access allowed'; exception when insufficient_privilege then null;end;
 begin perform public.manage_portal_accounts(a,'update',a,'{"name":"Self","role":"platform_analyst","disabled":false}'::jsonb||jsonb_build_object('expectedRevision',app_private.account_revision(a))); raise exception 'Self demotion allowed'; exception when insufficient_privilege then null;end;
 perform public.manage_portal_accounts(a,'update',b,'{"name":"Analyst","role":"platform_analyst","disabled":false}'::jsonb||jsonb_build_object('expectedRevision',app_private.account_revision(b)));
 result:=app_private.analysis_actor(b); assert result->>'organizationId' is null and result->>'admin'='false','Analyst scope';
 begin perform public.manage_portal_accounts(b,'list'); raise exception 'Analyst management allowed';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',b,'app_metadata',jsonb_build_object('role','platform_admin'))::text,true);
 assert not app_private.is_platform_admin(),'Old JWT keeps admin privileges';
 assert app_private.is_platform_analyst(),'Analyst permission absent';
 begin perform public.manage_survey(26,'inspect');raise exception 'Analyst survey mutation allowed';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('role','service_role','sub',a)::text,true);
 perform public.manage_portal_accounts(a,'update',b,'{"name":"Analyst","role":"platform_analyst","disabled":true}'::jsonb||jsonb_build_object('expectedRevision',app_private.account_revision(b)));
 begin perform app_private.analysis_actor(b);raise exception 'Disabled analyst access allowed';exception when insufficient_privilege then null;end;
 perform public.manage_portal_accounts(a,'update',c,'{"name":"Company","role":"company","disabled":true}'::jsonb||jsonb_build_object('expectedRevision',app_private.account_revision(c)));
 perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',c)::text,true);
 assert not app_private.is_organization_member(1),'Disabled membership retained access';
 perform set_config('request.jwt.claims',jsonb_build_object('role','authenticated','sub',a)::text,true);
 insert into survey_versions(id,name,reporting_year,updated_at) values(9001,'Unused draft',2026,now()-interval '1 second');
 result:=public.manage_survey(9001,'inspect');assert (result->>'canDelete')::boolean,'Unused draft cannot be deleted';
 stamp:=result->'survey'->>'updated_at';
 perform public.manage_survey(9001,'update',jsonb_build_object('name','Renamed draft','year',2027,'expectedUpdatedAt',stamp));
 assert (select name from survey_versions where id=9001)='Renamed draft','Rename failed';
 begin perform public.manage_survey(9001,'update',jsonb_build_object('name','Stale','year',2027,'expectedUpdatedAt',stamp));raise exception 'Stale edit accepted';exception when sqlstate 'PT409' then null;end;
 result:=public.manage_survey(26,'inspect');assert not (result->>'canDelete')::boolean,'Reports did not prevent deletion';
 begin perform public.manage_survey(26,'delete',jsonb_build_object('expectedUpdatedAt',result->'survey'->>'updated_at','confirmName',result->'survey'->>'name'));raise exception 'Used survey deleted';exception when raise_exception then if SQLERRM='Used survey deleted' then raise;end if;end;
 result:=public.manage_survey(9001,'inspect');
 perform public.manage_survey(9001,'delete',jsonb_build_object('expectedUpdatedAt',result->'survey'->>'updated_at','confirmName','Renamed draft'));
 assert not exists(select 1 from survey_versions where id=9001),'Delete failed';
 assert (select count(*) from audit_events where event_type like 'survey.%')=2,'Survey audit missing';
end;$$;
set local role authenticated;
do $$begin
 begin perform public.manage_portal_accounts('10000000-0000-4000-8000-000000000001','list');raise exception 'RPC directly accessible';exception when insufficient_privilege then null;end;
end;$$;
reset role;
rollback;
