-- Run only against tests/fixtures/analysis-database.sql on the isolated local server.
begin;
do $$ begin if current_setting('port')<>'55439' or current_database() not like 'analysis_v2_test%' then raise exception 'Local fixture database required';end if;end;$$;
select set_config('request.jwt.claims','{"role":"service_role"}',true);
do $$
declare a uuid:='10000000-0000-4000-8000-000000000001'; reviewer uuid:='10000000-0000-4000-8000-000000000002';
  company uuid:='10000000-0000-4000-8000-000000000003'; proposal jsonb; published jsonb; run jsonb; source jsonb; input jsonb;
  definition jsonb; denied boolean; copied uuid;
begin
  if (select count(*) from app_private.analysis_source_packs where dataset='synthetic')<>16 then raise exception 'Snapshot backfill mismatch'; end if;
  if has_function_privilege('authenticated','public.analysis_v2_run(uuid,text,uuid,jsonb,uuid)','EXECUTE') then raise exception 'Raw input gateway exposed'; end if;
  if has_table_privilege('authenticated','app_private.analysis_source_packs','SELECT') then raise exception 'Raw table exposed'; end if;
  if not app_private.analysis_snapshot_visibility(26,'[{"survey_question_id":1,"value":7}]','{"questionKey":"CTP25-006","operator":"equals","value":7}') then raise exception 'Visibility ignored snapshot value';end if;
  if app_private.analysis_snapshot_visibility(26,'[{"survey_question_id":1,"value":8}]','{"questionKey":"CTP25-006","operator":"equals","value":7}') then raise exception 'Visibility read a live answer';end if;
  definition:='{"metric":{"code":"workforce.headcount","name":"Employees","kind":"number","unit":"people","scope":"company","population":"employees","period":"year end","method":"headcount","options":[],"operations":["difference","percent_change"]},"dataset":"synthetic","relation":"equivalent","reason":"Synthetic fixture contract","sources":[{"questionId":1,"revisionId":1,"field":"","signature":"fixture-signature","transform":{"kind":"identity"}},{"questionId":2,"revisionId":1,"field":"","signature":"fixture-signature","transform":{"kind":"identity"}}]}';
  proposal:=public.analysis_v2_mapping(a,'propose',null,definition);
  denied:=false; begin perform public.analysis_v2_mapping(a,'publish',(proposal->>'id')::uuid,definition); exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'Self approval accepted'; end if;
  published:=public.analysis_v2_mapping(reviewer,'publish',(proposal->>'id')::uuid,definition);
  if jsonb_array_length(app_private.analysis_bindings())<>2 then raise exception 'Mapping sources missing'; end if;
  input:='{"years":[2024],"surveyVersionIds":[],"organizationIds":[],"questionKeys":[],"metricCodes":[],"datasetMode":"synthetic","cohortMode":"available_each_year"}';
  run:=public.analysis_v2_run(a,'create',null,input,'20000000-0000-4000-8000-000000000001');
  if run->>'id' is distinct from public.analysis_v2_run(a,'create',null,input,'20000000-0000-4000-8000-000000000001')->>'id' then raise exception 'Idempotency failed'; end if;
  source:=public.analysis_v2_run(a,'inputs',(run->>'id')::uuid);
  if jsonb_array_length(source->'packs')<>8 then raise exception 'Admin year filter failed'; end if;
  denied:=false; begin perform public.analysis_v2_run(company,'read',(run->>'id')::uuid); exception when insufficient_privilege then denied:=true; end;
  if not denied then raise exception 'Cross-user run visible'; end if;
  perform public.analysis_v2_run(a,'complete',(run->>'id')::uuid,'{"schemaVersion":2,"facts":[],"evidence":[]}');
  perform public.analysis_v2_narrative(a,'start',(run->>'id')::uuid,'{"model":"fixture","inputTokens":100,"outputTokens":100,"estimatedCost":1}');
  denied:=false; begin perform public.analysis_v2_narrative(a,'start',(run->>'id')::uuid,'{"model":"fixture","inputTokens":100,"outputTokens":100,"estimatedCost":1}'); exception when serialization_failure or sqlstate 'PT409' then denied:=true; end;
  if not denied then raise exception 'Duplicate provider reservation accepted'; end if;
  perform public.analysis_v2_narrative(a,'finish',(run->>'id')::uuid,'{"state":"outcome_unknown"}');
  if (select sum(coalesce(actual_cost_usd,estimated_cost_usd)) from ai_usage_events)<>1 then raise exception 'Unknown provider cost was released'; end if;
  denied:=false; begin insert into ai_usage_events(requested_by,request_type,model,estimated_cost_usd)values(a,'test','fixture',20); exception when raise_exception then denied:=true; end;
  if not denied then raise exception 'Budget overspend accepted'; end if;
  perform public.analysis_v2_mapping(reviewer,'revoke',(published->>'id')::uuid,'{"reason":"Definition requires correction"}');
  if not (public.analysis_v2_run(a,'read',(run->>'id')::uuid)->>'invalidated')::boolean then raise exception 'Revoked mapping did not invalidate result'; end if;
  if public.analysis_v2_run(a,'read',(run->>'id')::uuid)->'result'<>'null'::jsonb then raise exception 'Revoked result leaked'; end if;
  run:=public.analysis_v2_run(company,'create',null,input,'20000000-0000-4000-8000-000000000002');
  source:=public.analysis_v2_run(company,'inputs',(run->>'id')::uuid);
  if jsonb_array_length(source->'packs')<>16 then raise exception 'Fixed company publication was filtered before privacy validation'; end if;
  copied:=app_private.capture_analysis_source(1,'reconstructed');
  if (select count(*) from app_private.analysis_source_packs)<>16 then raise exception 'Identical capture duplicated source'; end if;
  update submission_snapshots set payload='[{"survey_question_id":1,"value":999}]' where id=1;
  if (select count(*) from app_private.analysis_source_packs)<>17 then raise exception 'Changed snapshot did not create new source'; end if;
  if (select payload->'questions'->0->'value' from app_private.analysis_source_packs where id=copied)='999'::jsonb then raise exception 'Source history overwritten'; end if;
  if not (public.analysis_v2_run(company,'read',(run->>'id')::uuid)->>'invalidated')::boolean then raise exception 'Changed publication did not invalidate saved access';end if;
  raise notice 'PASS: snapshot history, private privileges, two-admin review, scope, idempotency, run isolation, revocation, budget and provider reservation';
end; $$;
rollback;
